// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwtg4dpsEUfh5STIGfC9_TfV70RrB9rfs',
    appId: '1:4870927871:web:cfd4cba706d8f4142923ca',
    messagingSenderId: '4870927871',
    projectId: 'student-app-e0485',
    authDomain: 'student-app-e0485.firebaseapp.com',
    storageBucket: 'student-app-e0485.firebasestorage.app',
    measurementId: 'G-214X3MWZ9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgEYWieaVApaP3Z8UsX1vh_OJ6frpQZXI',
    appId: '1:4870927871:android:0cc39ecceb1212532923ca',
    messagingSenderId: '4870927871',
    projectId: 'student-app-e0485',
    storageBucket: 'student-app-e0485.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8Weev5HS-uFs4TSpOy1jBYPM_SL8wHLA',
    appId: '1:4870927871:ios:21caebb78cc06c582923ca',
    messagingSenderId: '4870927871',
    projectId: 'student-app-e0485',
    storageBucket: 'student-app-e0485.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8Weev5HS-uFs4TSpOy1jBYPM_SL8wHLA',
    appId: '1:4870927871:ios:21caebb78cc06c582923ca',
    messagingSenderId: '4870927871',
    projectId: 'student-app-e0485',
    storageBucket: 'student-app-e0485.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwtg4dpsEUfh5STIGfC9_TfV70RrB9rfs',
    appId: '1:4870927871:web:3f01bdc2b0735a282923ca',
    messagingSenderId: '4870927871',
    projectId: 'student-app-e0485',
    authDomain: 'student-app-e0485.firebaseapp.com',
    storageBucket: 'student-app-e0485.firebasestorage.app',
    measurementId: 'G-8ZCJMQH28N',
  );
}
